const router = require('express').Router()
const imageUpload = require('../Controller/Providers/ImageUpload')
const registration = require('../Controller/Providers/Registration')
const allProviders = require('../Controller/Providers/AllProviders')
const getProviderByID = require('../Controller/Providers/GetProviderByID')
const login = require('../Controller/Providers/Login')
const getAppointments = require('../Controller/Providers/getAppointment')
const postRating = require('../Controller/Providers/postRating')
const markAppointmentComplete = require('../Controller/Providers/AppComplete')
const jwtVerify = require('../Controller/JwtVerify/JwtVerify')

router.post('/post/provider/uploadImageResume', imageUpload)
router.post('/post/provider/register', registration)
router.get('/get/provider/AllProviders', allProviders)
router.get('/get/provider/:id', getProviderByID)
router.post('/post/login/provider', login)
router.get('/get/provider/appointments/:id', jwtVerify, getAppointments)
router.post('/post/provider/rating', jwtVerify, postRating)
router.delete('/delete/appointment:id', jwtVerify, markAppointmentComplete)

module.exports = router
