const router = require('express').Router()
const imageUpload = require('../Controller/Providers/ImageUpload')
const registration = require('../Controller/Providers/Registration')
const allProviders = require('../Controller/Providers/AllProviders')
const getProviderByID = require('../Controller/Providers/GetProviderByID')
const getSchedule = require('../Controller/Providers/GetSchedule')
const getScheduleById = require('../Controller/Providers/GetScheduleById')
const login = require('../Controller/Providers/Login')
const getAppointments = require('../Controller/Providers/getAppointment')

router.post('/post/provider/uploadImageResume', imageUpload)
router.post('/post/provider/register', registration)
router.get('/get/provider/AllProviders', allProviders)
router.get('/get/provider/schedule', getSchedule)
router.get('/get/provider/schedule/:id', getScheduleById)
router.get('/get/provider/:id', getProviderByID)
router.post('/post/login/provider', login)
router.get('/get/provider/appointments/:id', getAppointments)

module.exports = router
